version = 0.1

[default.deploy.parameters]
stack_name = "carscan1"
resolve_s3 = true
s3_prefix = "carscan1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"stage\" CustomDomainName=\"carscan.nitroba.com\" HostedZoneId=\"Z05629322DW2WL7JUPCBJ\" CertificateArn=\"\" LogLevel=\"DEBUG\" DeploymentTimestamp=\"2026-01-28\" GoogleClientSecretArn=\"arn2\" BrivoApiKeyArn=\"arn3\""
image_repositories = []
confirm_changeset = true
profile = "simsong"

[default.global.parameters]
region = "us-east-1"
