#
# Deploy with:
# sam deploy --profile fas
# or put this in samconfig.toml:
# [default.deploy.parameters]
# profile = "fas"

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  License Plate Scanner (BasisTech/Brivo)
  Google OAuth, Server-side LPR, Secrets Manager

Globals:
  Function:
    Architectures: [ arm64 ]
    Environment:
      Variables:
        LOG_LEVEL: !Ref LogLevel
        DEPLOYMENT_TIMESTAMP: !Ref DeploymentTimestamp
        TABLE_NAME: !Ref MyTable
        BUCKET_NAME: !Ref UploadBucket
        GOOGLE_SECRET_ARN: !Ref GoogleClientSecretArt
        BRIVO_SECRET_ARN: !Ref BrivoApiKeyArn

Parameters:
  StageName:
    Type: String
    Default: stage
    AllowedValues: [prod, stage]
    Description: The deployment environment (prod or stage).
  HostedZoneId:
    Type: String
    Description: Route53 Zone ID
  CertificateArn:
    Type: String
    Default: ""
    Description: (Optional) ACM Certificate ARN for the domain. Leave blank to auto-create.
  LogLevel:
    Type: String
    Default: INFO
    AllowedValues: [CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET]
    Description: Default LOG_LEVEL environment value for the function
  DeploymentTimestamp:
    Type: String
    Description: UTC timestamp of when the application was deployed.
    Default: 'Not Set'
  GoogleClientSecretArn:
    Type: String
    NoEcho: true
    Description: "Google OAuth Client Secret Arn"
  BrivoApiKeyArn:
    Type: String
    NoEcho: true
    Description: "Brivo API Key Arn"

Mappings:
  EnvConfig:
    prod:
      DomainName: "v1.cybersecurity-policy.org"
      StageName: "prod"
      Description: "Cybersecurity Policy Home"
      CustomDomainUrl: "https://v1.cybersecurity-policy.org/"
    stage:
      DomainName: "v2.cybersecurity-policy.org"
      StageName: "stage"
      Description: "Cybersecurity Policy Stage"
      CustomDomainUrl: "https://v2.cybersecurity-policy.org/"

Conditions:
  CreateAcmCert: !Equals [!Ref CertificateArn, ""]

Resources:
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Required for EventBridge triggers
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
  HomeCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: CreateAcmCert
    Properties:
      DomainName: !FindInMap [EnvConfig, !Ref StageName, DomainName]
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !FindInMap [EnvConfig, !Ref StageName, DomainName]
          HostedZoneId: !Ref HostedZoneId

  # HTTP API fronting the Lambda, bound to specified domain
  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins: ['*']
        AllowMethods: ['GET','POST','OPTIONS']
      Domain:
        DomainName: !FindInMap [EnvConfig, !Ref StageName, DomainName]
        CertificateArn: !If [CreateAcmCert, !Ref HomeCertificate, !Ref CertificateArn]
        Route53:
          HostedZoneId: !Ref HostedZoneId

  MyWebFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: "API Gateway for Lambda Powertools application"
      Runtime: python3.13
      CodeUri: src/
      Handler: app.main.lambda_handler
      Timeout: 60
      MemorySize: 512
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref UploadBucket
        - DynamoDBCrudPolicy:
            TableName: cala-garage-scans
        - RekognitionDetectOnlyPolicy: {}
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /{proxy+}
            Method: ANY
        # S3 Upload Trigger via EventBridge
        S3UploadEvent:
          Type: EventBridgeRule
          Properties:
            InputPath: $.detail
            Pattern:
              source: [ "aws.s3" ]
              detail-type: [ "Object Created" ]
              detail:
                bucket:
                  name: [ !Ref UploadBucket ]
                object:
                  key: [ { "prefix": "uploads/" } ]

Outputs:
  ApiId:
    Description: HTTP API ID
    Value: !Ref MyHttpApi
  URL:
    Description: URL
    Value: !FindInMap [EnvConfig, !Ref StageName, DomainName]
